### ISSUE TITLE
 Hangman Game

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#10]
Write a Python script for a text-based Hangman game.

**Comment by Transyltooniaa** [comment]
I'm interested in working on this issue # . After reviewing the requirements and understanding the scope of the task, I'd like to take ownership of this issue and work towards resolving it.

I have the necessary skills and expertise to address this issue effectively, and I'm excited to contribute to the project. If there are any specific guidelines or suggestions you have for approaching this task, please feel free to let me know, and I'll ensure to follow them closely.

Please consider assigning this issue to me, and I'll start working on it promptly. If there are any additional details or discussions required, I'm more than happy to engage with the community and the project maintainers.

Thank you for your time and for maintaining this project. I look forward to contributing to its progress.

**Comment by Transyltooniaa** [comment]
Can I complete this by tomorrow evening if it is fine with you. I have midsem exams going right now

**Comment by Transyltooniaa** [comment]
Also could you please provide an elaboration of the project, including details about the types of words to be chosen? I appreciate your assistance in advance. Kindly ensure that the explanation is thorough to prevent any potential confusion and to achieve the best possible results.

**Comment by Transyltooniaa** [comment]
Also could you please provide an elaboration of the project, including details about the types of words to be chosen or number of strikes in the hangman or what all data should be available to the user while guessing the words? I appreciate your assistance in advance. Kindly ensure that the explanation is thorough to prevent any potential confusion and to achieve the best possible results.

**Comment by Swapnil-Singh-99** [comment]
👋  @Transyltooniaa This issue is closed.
Don't forget to give a ⭐️ & Happy coding!. 😊
