### ISSUE TITLE
Build a script that automates sending emails with custom content

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#100]

**Comment by mariyam-siddiqui** [comment]
Hey! i would like to work on this. Can this be assigned to me?

**Comment by mariyam-siddiqui** [comment]
Hey! I have made the changes and raised PR for the same. 
AutomaticEmail #134 - https://github.com/Swapnil-Singh-99/PythonScriptsHub/pull/134
