### ISSUE TITLE
Create a script for managing a virtual book library, including book information, borrowing, and returning.

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#103]

**Comment by amanmakhija** [comment]
Hey @Swapnil-Singh-99 ,

Can you please assign this issue to me ASAP? I have completed the script and am ready to push it as soon as it is assigned to me.

Thanks.

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija You can start working on the issue
