### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#11]
Build a Python script that can solve Sudoku puzzles.

**Comment by Swapnil-Singh-99** [comment]
👋 Feel free to leave a comment below if you'd like to work on this issue or create new issue if you have an idea. We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Azzedde** [comment]
Hello, I'd like to work on this issue, can you assign it to me please ?

**Comment by Swapnil-Singh-99** [comment]
@Azzedde Any updates ?

**Comment by Azzedde** [comment]
I'm working on it, worked already on a linear programming approach. And now i'm trying to optimize it using heuristics to increase performance. I will PR asap

**Comment by Swapnil-Singh-99** [comment]
Good Job 👍

Don't forget to give a ⭐️ & Happy coding!. 😊
