### ISSUE TITLE
Build a classic snake game where the player controls a snake to eat food and grow.

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#112]

**Comment by Kallind** [comment]
hey, can i work on this?

**Comment by Kallind** [comment]
i have made the game and sent a pull request

**Comment by Kallind** [comment]
@Swapnil-Singh-99 please check i have created a new PR with only snake game

**Comment by Kallind** [comment]
@Swapnil-Singh-99 was facing some issue with the old PR i have made a new PR without the story.py and only snake game. 
Please review it. Thank you

**Comment by amanmakhija** [comment]
Hey @Swapnil-Singh-99 ,

If no one is working on this issue then can I get assigned?

Thanks.

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija Go for it
