### ISSUE TITLE
ASCII Art Generator

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#13]
Create a Python script that converts text into ASCII art.

**Comment by Swapnil-Singh-99** [comment]
👋 Feel free to leave a comment below if you'd like to work on this issue or create new issue if you have an idea. We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Noazs** [comment]
Hello, I would like to take this issue.

**Comment by Parvezkhan0** [comment]
can you also assign this issue to me?

**Comment by VishnuAmit** [comment]
Hey @Swapnil-Singh-99 . id like to work on this issue if it is available. Will finish it ASAP.
Thanks !

**Comment by Sa2003hil** [comment]
Hello **@Swapnil-Singh-99** ,

I would like to take ownership of ASCII Art Generator and work on this issue, I kindly request that this issue be assigned to me.

Thank you for your assistance!

Best regards,
@Sa2003hil

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 Are you doing this issue?

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 Yes, please assign this issue to me

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 
You have been assigned the issue.
We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 Please update the status of the issue?

**Comment by amanmakhija** [comment]
Hey @Swapnil-Singh-99 ,

If no one is working on this issue can you assign this issue to me? I have already done working on this issue.

Thanks.

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija Go for it
