### ISSUE TITLE
Face Registration and Recognition

### ISSUE THREAD

**Issue by amanmakhija** [Swapnil-Singh-99/PythonScriptsHub#137]
Hey, @Swapnil-Singh-99 

I want to contribute a script that can register the user's face and name, and another script that can recognize the user using the face encodings present in the database and will also tell the name of the user if recognized else will tell unknown.
Please add a hacktoberfest label and assign this issue to me.

Regards,
@amanmakhija

**Comment by Swapnil-Singh-99** [comment]
@amanmakhija Yes you can start working on it
Good Luck 👍
