### ISSUE TITLE
Password Strength Checker

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#14]
Create a Python script that evaluates the strength of a password based on certain criteria.

**Comment by Swapnil-Singh-99** [comment]
👋 Feel free to leave a comment below if you'd like to work on this issue or create new issue if you have an idea. We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by yekxp** [comment]
Hello, I am a student of Technical University in Kosice and I would like to take this problem, I would also like to add tests to this python checker.  Would it be possible?

**Comment by Transyltooniaa** [comment]
I'm interested in working on this issue #14 . After reviewing the requirements and understanding the scope of the task, I'd like to take ownership of this issue and work towards resolving it.

Please consider assigning this issue to me, and I'll start working on it promptly. If there are any additional details or discussions required, I'm more than happy to engage with the community and the project maintainers.

Thank you for your time and for maintaining this project. I look forward to contributing to its progress.

**Comment by Parvezkhan0** [comment]
please include label hacktoberfest in this issue

**Comment by Transyltooniaa** [comment]
@Parvezkhan0 you cannot create a pull request until assigned to you...  I asked for the project first. Please let the owner decide who can fix this issue. Therefore I request you to close your PR.

**Comment by Transyltooniaa** [comment]
@Swapnil-Singh-99 Cn you assign me this issue 🙏🏻 . And if possible please add the hacktoberfest label
