### ISSUE TITLE
Countdown Timer GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#15]
Develop a Python script that counts down from a specified time duration.

**Comment by Swapnil-Singh-99** [comment]
👋 Feel free to leave a comment below if you'd like to work on this issue or create new issue if you have an idea. We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by Transyltooniaa** [comment]
I'm interested in working on this issue https://github.com/Swapnil-Singh-99/PythonScriptsHub/issues/14 . After reviewing the requirements and understanding the scope of the task, I'd like to take ownership of this issue and work towards resolving it.

Please consider assigning this issue to me, and I'll start working on it promptly. If there are any additional details or discussions required, I'm more than happy to engage with the community and the project maintainers.

Thank you for your time and for maintaining this project. I look forward to contributing to its progress

**Comment by Transyltooniaa** [comment]
Just to clarify this script has to be GUI based right? Thanks in advance !

**Comment by Swapnil-Singh-99** [comment]
@Transyltooniaa Yes
