### ISSUE TITLE
Dice Rolling Simulator GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#16]
Create a Python script that simulates rolling a six-sided die and displays the result.

**Comment by Swapnil-Singh-99** [comment]
👋 Feel free to leave a comment below if you'd like to work on this issue or create new issue if you have an idea. We welcome your contributions! 😊

Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by aryanas159** [comment]
Can I work on this?

**Comment by Parvezkhan0** [comment]
please include label hacktoberfest in this issue
