### ISSUE TITLE
Inventory Management System

### ISSUE THREAD

**Issue by kamitabh24** [Swapnil-Singh-99/PythonScriptsHub#167]
Can i get this issue assigned to me this is a inventory management system using industry 4.0 its a machine learning nlp project

**Comment by kamitabh24** [comment]
Done created 
[package.json](https://github.com/Swapnil-Singh-99/PythonScriptsHub/files/13198754/package.json)

**Comment by Swapnil-Singh-99** [comment]
Please create a Pull Request

**Comment by kamitabh24** [comment]
done created pull request 
https://github.com/kamitabh24/PythonScriptsHub/pull/2/commits/bcd717132fda16e044e31bb2706058e93bcc12b9

**Comment by Swapnil-Singh-99** [comment]
Please compare a pull request on my repository

**Comment by kamitabh24** [comment]
done sir https://github.com/Swapnil-Singh-99/PythonScriptsHub/pull/185

**Comment by kamitabh24** [comment]
done sir https://github.com/Swapnil-Singh-99/PythonScriptsHub/pull/187
