### ISSUE TITLE
Temperature Converter GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#17]
Build a Python script that converts between Fahrenheit and Celsius temperatures.

**Comment by aryanas159** [comment]
Do we need only the python script or GUI is also required?

**Comment by Swapnil-Singh-99** [comment]
@aryanas159 Script will also work but will be better if GUI is implemented

**Comment by Swapnil-Singh-99** [comment]
Would you like to work on this issue?

**Comment by aryanas159** [comment]
> Would you like to work on this issue?

sure
