### ISSUE TITLE
Fix Github Action Workflows | auto_assign.yml

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#29]
# Fix
/assign or other comments should only work if the issue is not assigned to someone

![image](https://github.com/Swapnil-Singh-99/PythonScriptsHub/assets/85278243/2aef377e-6682-4220-8c4a-5df212bc9c6c)

**Comment by aryanas159** [comment]
@Swapnil-Singh-99 I don't think there's anything wrong with this script.

**Comment by Swapnil-Singh-99** [comment]
@aryanas159 Are you working on this issue?

**Comment by aryanas159** [comment]
> @aryanas159 Are you working on this issue?

Yeah. I tried assigning myself the issue with a new account, but it didn't work, it seems to be working fine.

**Comment by Swapnil-Singh-99** [comment]
> > @aryanas159 Are you working on this issue?
> 
> Yeah. I tried assigning myself the issue with a new account, but it didn't work, it seems to be working fine.

You have to fix auto_comment.yml
the script should send a different message when the maintainers create an issue 
and another message when other user create issues
