### ISSUE TITLE
create a wheather app using command line

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#66]

**Comment by ayan-joshi** [comment]
@Swapnil-Singh-99 please assign me this issue I'll work on it and please add the hacktoberfest label

**Comment by shreyanshig** [comment]
Can you assign this task to me?

**Comment by Swapnil-Singh-99** [comment]
> Can you assign this task to me?

You have been assigned this task please start working on it
