### ISSUE TITLE
make a rock paper scissors game

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#68]

**Comment by ayan-joshi** [comment]
I can work on this assign it to me and add hacktoberfest label @Swapnil-Singh-99

**Comment by VishnuAmit** [comment]
I can work on this and deliver you by today. Please assign it to me @Swapnil-Singh-99

**Comment by VishnuAmit** [comment]
@Swapnil-Singh-99 Before coding, I have a doubt. any preferred coding language ?

**Comment by VishnuAmit** [comment]
hey @Swapnil-Singh-99 . I have done improvements in the game. Please go check my PR
