### ISSUE TITLE
Calculator GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#8]
Make a calculator GUI using tkinter

**Comment by Vidip-Ghosh** [comment]
Can I work on this?

**Comment by Parvezkhan0** [comment]
can you also assign this issue to me?

**Comment by shubhankar1313** [comment]
Can you please assign this issue to me as well?

**Comment by Swapnil-Singh-99** [comment]
@Vidip-Ghosh Are you working on this issue ?

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh Are you working on this issue ?

Yes

**Comment by Abhipsa05** [comment]
I can create calculator using PySide6. Can I contribute here?

**Comment by Swapnil-Singh-99** [comment]
> I can create calculator using PySide6. Can I contribute here?

@Abhipsa05 someone is working on this issue, you can work on some other issue or create our own issue
