### ISSUE TITLE
[feat]: Parallel Processing with Multiprocessing

### ISSUE THREAD

**Issue by Parvezkhan0** [Swapnil-Singh-99/PythonScriptsHub#80]
Write a Python program that uses the multiprocessing module to perform parallel processing on a large dataset. The program should split the data into multiple chunks and process them concurrently. Ensure that the results are correctly aggregated.

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99  Please assign me this issue as a part to my hacktoberfest contribution

**Comment by Swapnil-Singh-99** [comment]
You can start working on the issue !
Don't forget to give a ⭐️ & Happy coding!. 😊
