### ISSUE TITLE
[feat]: Concurrent File Processing

### ISSUE THREAD

**Issue by Parvezkhan0** [Swapnil-Singh-99/PythonScriptsHub#85]
Write a program that reads a large file and processes its content concurrently using threads or processes. Ensure that the file is read and processed efficiently.

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 assign me this issue for hactoberfest

**Comment by Swapnil-Singh-99** [comment]
Please include example files also and a readme file
