### ISSUE TITLE
[feat]: Optimized Sorting Algorithm

### ISSUE THREAD

**Issue by Parvezkhan0** [Swapnil-Singh-99/PythonScriptsHub#86]
Implement a highly optimized sorting algorithm (e.g., radix sort, shell sort) and compare its performance against standard sorting algorithms (e.g., quicksort, mergesort).

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 assign me this issue for hacktoberfest

**Comment by Swapnil-Singh-99** [comment]
Complete two issue first

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 I have completed my two issue, please assign me this issue

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 Please label it with hacktoberfest
