### ISSUE TITLE
[feat]: Distributed Computing with PySpark

### ISSUE THREAD

**Issue by Parvezkhan0** [Swapnil-Singh-99/PythonScriptsHub#88]
Write a program that performs a complex data transformation using PySpark on a distributed dataset. Optimize the transformation process for performance.

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 assign me this issue for hacktoberfest

**Comment by Swapnil-Singh-99** [comment]
Complete two issue first

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 i have completed my two issue please assign me this issue

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 Please label it with hacktoberfest
