### ISSUE TITLE
[feat]:Dynamic Programming Challenge

### ISSUE THREAD

**Issue by Parvezkhan0** [Swapnil-Singh-99/PythonScriptsHub#89]
Provide a problem that requires solving using dynamic programming. The problem should be non-trivial and may involve complex optimization.

**Comment by Parvezkhan0** [comment]
@Swapnil-Singh-99 assign me this issue for hacktoberfest

**Comment by Swapnil-Singh-99** [comment]
Complete two issue first

**Comment by Swapnil-Singh-99** [comment]
@Parvezkhan0 Please update the status of the issue.
