### ISSUE TITLE
To-Do List GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Swapnil-Singh-99/PythonScriptsHub#9]
Create a GUI script that allows users to add, remove, and list tasks in a to-do list.

**Comment by Transyltooniaa** [comment]
> Create a GUI script that allows users to add, remove, and list tasks in a to-do list.

I'm interested in working on this issue . After reviewing the requirements and understanding the scope of the task, I'd like to take ownership of this issue and work towards resolving it.

I have the necessary skills and expertise to address this issue effectively, and I'm excited to contribute to the project. If there are any specific guidelines or suggestions you have for approaching this task, please feel free to let me know, and I'll ensure to follow them closely.

Please consider assigning this issue to me, and I'll start working on it promptly. If there are any additional details or discussions required, I'm more than happy to engage with the community and the project maintainers.

Thank you for your time and for maintaining this project. I look forward to contributing to its progress.

Best regards,
Ajitesh Kumar Singh 


Also if my pr gets accepted will it count as a hacktoberfest contribution ?

**Comment by Swapnil-Singh-99** [comment]
> > Create a GUI script that allows users to add, remove, and list tasks in a to-do list.
> 
> I'm interested in working on this issue . After reviewing the requirements and understanding the scope of the task, I'd like to take ownership of this issue and work towards resolving it.
> 
> I have the necessary skills and expertise to address this issue effectively, and I'm excited to contribute to the project. If there are any specific guidelines or suggestions you have for approaching this task, please feel free to let me know, and I'll ensure to follow them closely.
> 
> Please consider assigning this issue to me, and I'll start working on it promptly. If there are any additional details or discussions required, I'm more than happy to engage with the community and the project maintainers.
> 
> Thank you for your time and for maintaining this project. I look forward to contributing to its progress.
> 
> Best regards, Ajitesh Kumar Singh
> 
> Also if my pr gets accepted will it count as a hacktoberfest contribution ?

Yes our PR when merged will count towards hacktoberfest

**Comment by Transyltooniaa** [comment]
So can I start now ... I have the code ready ... do i create a pull request ?

**Comment by Swapnil-Singh-99** [comment]
> So can I start now ... I have the code ready ... do i create a pull request ?
Yes you can

**Comment by Swapnil-Singh-99** [comment]
Please don't forget to ⭐️ the repository
Happy coding!. 😊

**Comment by Transyltooniaa** [comment]
So now my hacktoberfest Id will show that 1 pr has been merged ?

**Comment by Swapnil-Singh-99** [comment]
Yes, it will take time to update
