### ISSUE TITLE
Create a handwritten digit recognizer program(use tkinter/pytorch)

### ISSUE THREAD

**Issue by flowerfalling** [Swapnil-Singh-99/PythonScriptsHub#93]
If it passes, I would like to ask if I should put the trained parameter file into PR?(File size does not exceed 1mb)

**Comment by Swapnil-Singh-99** [comment]
Don't forget to give a ⭐️ & Happy coding!. 😊

**Comment by flowerfalling** [comment]
I would like to ask if I should put the trained parameter file into PR?(File size does not exceed 1mb)
